version: '3.8'
services:
  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: audiocleanuser
      POSTGRES_PASSWORD: audiocleanpassword
      POSTGRES_DB: audiocleandb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
